server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456
  redis:
    database: 0
    #host: 172.16.13.130
    host: 127.0.0.1
    port: 6379
    #password: redis
    #sentinel:   #哨兵模式
     # master: wwq-master
     # nodes: 172.16.13.130:26379,172.16.13.120:26379
    #cluster:    集群模式
    #  nodes: 172.16.13.130:6379,172.16.13.120:6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl